version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "07:45"
      timezone: UTC
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
