name: Build
on:
  pull_request:
    paths:
      - "**.nix"
      - flake.lock
      - .github/workflows/build.yml
  push:
    paths:
      - "**.nix"
      - flake.lock
      - .github/workflows/build.yml
jobs:
  tests:
    strategy:
      matrix:
        nixPath:
          - nixpkgs=channel:nixos-unstable
          - nixpkgs=channel:nixpkgs-unstable
          - nixpkgs=channel:nixos-20.09
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: "${{ matrix.nixPath }}"
      - name: Show nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      - name: Build nix packages
        run: nix-build ci.nix -A buildOutputs
